### ISSUE TITLE
Can't get children to pass properly.

### ISSUE THREAD

**Issue by Industrial** [developit/htm#57] opened 2018-12-29 17:42 UTC
Hi.

https://codesandbox.io/s/nwkqyly08j

There is my example.

I added a simple function component that just returns the children. It doesn't work. What am I doing wrong?

**Comment by Industrial** [comment] 2018-12-29 18:06
It is solved by `const X = ({ children }) => children[0]`. Why can't it be an array, though?

**Comment by Industrial** [comment] 2018-12-29 18:31
I'm running into many problems with libraries. Right now with Material UI.

example: `Warning: Failed prop type: Invalid prop `children` supplied to `Grid`, expected a ReactNode.
    in Grid`

**Comment by Industrial** [comment] 2018-12-29 20:14
I tried http://recharts.org/en-US/ as an example and 

```
  <${LineChart} width=${500} height=${300} data=${[0, 1, 2, 3, 4, 5, 4, 3, 4, 5, 4, 3, 2, 1, 0]}>
    <${XAxis} dataKey="name" />
    <${YAxis} />
    <${CartesianGrid} stroke="#eee" strokeDasharray="5 5" />
    <${Line} type="monotone" dataKey="uv" stroke="#8884d8" />
    <${Line} type="monotone" dataKey="pv" stroke="#82ca9d" />
  <//>
```

gives me

`Uncaught Error: Objects are not valid as a React child (found: object with keys {nodeName, children, attributes, key}). If you meant to render a collection of children, use an array instead.`

**Comment by developit** [comment] 2019-01-07 22:44
@Industrial are you using Preact, or React? AFAIK Material-UI has issues with the current version of Preact, independent of HTM.

**Comment by Industrial** [comment] 2019-01-07 23:33
That was with Preact, yeah.

**Comment by developit** [comment] 2019-02-03 22:31
@kilianc with the binding corrected, can we close this issue?

@Industrial the current version of Preact does not support returning multiple roots from a component render, which is what returning `props.children` (an Array) would be. This is implemented in the upcoming Preact X, as it is backed by the same logic used for Fragments.

**Comment by developit** [comment] 2019-02-03 22:31
Closing since this seems like a duplicate of a bunch of Preact fragments related issues, but feel free to re-open if I'm missing something!

**Closed by developit** 2019-02-03 22:31 UTC
Labels: question
